name: FTP Deploy
on:
  push:
    branches:
      - master # Hangi branch'e push yapınca çalışsın?

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./ # Hostingdeki hedef klasör
          timeout: 190000
          #port: 21
          #protocol: ftp 
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            node_modules/**
            README.md
            .gitignore
            AI_GUIDE.md
            kisisel_web_sitesi_prompt_statiktir.md
